### ISSUE TITLE
What dataset do you use?

### ISSUE THREAD

**Issue by zoe218** [Belval/CRNN#1]
hello, I want to run your project, but I dont know choose which dataset, can you help me? Thanks a lot @Belval

**Comment by Belval** [comment]
@zoe218 I am still working on this project unfortunately so I'm afraid there isn't much to run (because the training part isn't implemented yet). 

During development I used [Synth90k](http://www.robots.ox.ac.uk/~vgg/data/text/) but it only contained words and not sentences so I had to take a break and make my own data generator that you can see/clone here:

https://github.com/Belval/TextRecognitionDataGenerator

The project should be completed.shortly. If you need a CRNN right now you can look at :

https://github.com/AimeeKing/crnn-tensorflow

Which seems to work but only for single words (which wasn't the scope of my project, as I want full sentences).

Hopefully that answers your questions. If I were to give an estimate I'd say the project should be in working condition in less than 2 weeks.

**Comment by zoe218** [comment]
hah, thanks a lot, best wish for you and your project~waiting~~~ @Belval

**Comment by songwendong** [comment]
Cannot convergence using this codeI 
I train model  more than 50W steps, the network cannot convergence, the edit lengths are always large
Any suggestions? I am new at deep learning.

**Comment by Belval** [comment]
@songwengdong very sorry but I believe you should read my answer to Zoe. The project is **not** ready, only the inference.

I would invite you to take a look at [crnn-tensorflow](https://github.com/AimeeKing/crnn-tensorflow) which is in working condition.

I expect to complete everything in the coming week but I had to take the time to generate synthetic data for training.

**Comment by songwendong** [comment]
thank you @Belval , crnn-tensorflowd doesn't work ，When running, it will be reported wrong,Can you teach me how to use crnn-tensorflowd?

**Comment by Belval** [comment]
@songwendong I wasn't aware that it didn't work. I would recommend opening an issue on their repository as I would not be able to help you.
